// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025-09-02, 6:32:12 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/jesse/Documents/github/webmaster_remake/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/plugins/**/*.{js,ts,mjs}","C:/Users/jesse/Documents/github/webmaster_remake/composables/**/*.{js,ts,mjs}","C:/Users/jesse/Documents/github/webmaster_remake/utils/**/*.{js,ts,mjs}","C:/Users/jesse/Documents/github/webmaster_remake/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jesse/Documents/github/webmaster_remake/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;